import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import Head from "next/head";
import "./globals.scss";

const fireCode = Fira_Code({
  variable: "--font-fira-code",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Git | Code Craft",
  description: "Generated by code craft",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <Head>
        <link rel="icon" href="/assets/icons/favicon.ico" />
        <link rel="icon" type="image/png" sizes="32x32" href="/assets/icons/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/assets/icons/favicon-16x16.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="/assets/icons/apple-touch-icon.png" />
        <link rel="manifest" href="/assets/icons/site.webmanifest" />
      </Head>
      <body
        className={`${fireCode.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
